# These are supported funding model platforms
## Funding

Thank you for considering supporting the Orange Farm Chamber of Businesses Directory! Your contribution will help us maintain and improve this directory, ensuring it remains a valuable resource for the community.

### Funding Goals

* **Server and infrastructure costs**: $100/month
* **Development and maintenance**: $500/month
* **Marketing and outreach**: $200/month

### Funding Options

* **GitHub Sponsors**: [Become a sponsor](https://github.com/sponsors/Orange-Farm-Chamber-of-Businesses-Directory)
* **Open Collective**: [Contribute via Open Collective](https://opencollective.com/Orange-Farm-Chamber-of-Businesses-Directory)
* **PayPal**: [Donate via PayPal](https://www.paypal.com/donate/?hosted_button_id=HSU9F9SF8JHAQ)

### Sponsorship Tiers

* **Bronze**: $10/month - Recognition on our sponsors page
* **Silver**: $50/month - Recognition on our sponsors page, logo on our website
* **Gold**: $100/month - Recognition on our sponsors page, logo on our website, featured business listing

### Budget Transparency

We are committed to transparency in our funding. Our budget will be publicly available, showing how funds are allocated and spent.

Thank you again for considering supporting the Orange Farm Chamber of Businesses Directory!
